-- Query: rating_features.sql
-- Descripción: Consulta datos completos de rating desde Snowflake (NEURON_PRO)
--
-- Tablas principales:
--   - T_EVALUACION: Evaluaciones de rating
--   - T_RATING_REQUEST: Solicitudes de rating
--   - T_CLIENTE: Datos maestros de clientes
--   - T_MODEL_RESPONSE: Respuestas del modelo (PD)
--   - T_LIMITES_NEG: Límites por negocio
--   - T_LIMITES_GE: Límites generales
--   - T_ESTADO_MOROSO: Estado de morosidad/ASNEF
--   - T_EEFF: Estados financieros España
--   - T_EEFF_PT: Estados financieros Portugal
--   - T_RIESGO_VIVO: Riesgo vivo por producto
--   - CRM/Salesforce: Ofertas y contratos
--
-- Parámetros: Ninguno (query estática, filtros aplicados en Python)

WITH RATING AS (
SELECT *
        FROM (
        SELECT
            T_EVALUACION.ID_EVALUACION,
            T_EVALUACION.FECHA_CREACION,
            LEFT(T_EVALUACION.FECHA_CREACION, 7) AS ANO_MES_CREACION,
            T_RATING_REQUEST.RATING_ID,
            T_RATING_REQUEST.ESTADO,
            T_RATING_REQUEST.ESTADO_DETALLE,
            T_RATING_REQUEST.ID_CLIENTE,
            T_RATING_REQUEST.LAST_REQUEST,
            T_RATING_REQUEST.GRADE_OLD,
            T_RATING_REQUEST.PD_OLD,
            T_MODEL_RESPONSE.DEFAULT_PROBABILITY AS PD_NEW,
            T_CLIENTE.CIF_NIF,
            T_CLIENTE.ZONA_GEOGRAFICA,
            T_CLIENTE.TIPO_PERSONA,
            T_LIMITES_NEG.VOLUMEN,
            T_LIMITES_NEG.ID_TRAMO,
            T_LIMITES_NEG.ID_NEGOCIO,
            T_LIMITES_NEG.VOLUMEN_MAXIMO,
            T_LIMITES_NEG.PRECIO,
            T_LIMITES_GE.LIMITE_TOTAL_CONCEDIDO,
            T_LIMITES_GE.LIMITE_DISPONIBLE_GE,
            T_ESTADO_MOROSO.CONCURSO,
            T_ESTADO_MOROSO.BUROFAX,
            T_ESTADO_MOROSO.DEUDA_ASNEF,
            T_ESTADO_MOROSO.ASNEF,
            T_EEFF.GASTOS_FINANCIEROS,
            T_EEFF.ING_EXPLOTACION,
            T_EEFF.RESULT_ANTES_IMP,
            T_EEFF.IMPORTE_NETO,
            T_EEFF.TOTAL_PASIVO,
            T_EEFF.FONDOS_PROPIOS,
            T_EEFF.FECHA_BALANCE,
            T_EEFF.FECHA_CONSTITUCION,
            T_EEFF.FECHA_CONTRATACION,
            T_EEFF.CODIGO_CNAE,
            RESULT_ANTES_IMP_PT,
            FECHA_BALANCE_PT,
            TOTAL_PASIVO_PT,
            FONDOS_PROPIOS_PT,
            FECHA_CONSTITUCION_PT,
            ING_EXPLOTACION_PT,
            IMPORTE_NETO_PT,
            GASTOS_FINANCIEROS_PT
        FROM "NEURON_PRO"."RATING"."T_EVALUACION" T_EVALUACION
        LEFT JOIN (
            SELECT
                id_evaluacion,
                MIN(T_RATING_REQUEST.RATING_ID) AS RATING_ID,
                MIN(T_RATING_REQUEST.ESTADO) AS ESTADO,
                MIN(T_RATING_REQUEST.ESTADO_DETALLE) AS ESTADO_DETALLE,
                T_RATING_REQUEST.ID_CLIENTE,
                T_RATING_REQUEST.ID_INPUT_CUSTOM_DATA,
                T_RATING_REQUEST.LAST_REQUEST,
                T_RATING_REQUEST.GRADE AS GRADE_OLD,
                T_RATING_REQUEST.PD AS PD_OLD,
                MAX(T_RATING_REQUEST.ID_RATING_REQUEST) AS MAX_ID_RATING_REQUEST -- Add MAX here
        FROM "NEURON_PRO"."RATING"."T_RATING_REQUEST" T_RATING_REQUEST
        WHERE LAST_REQUEST = 'TRUE' AND ID_INPUT_CUSTOM_DATA IS NULL
        AND T_RATING_REQUEST.ID_RATING_REQUEST = (
            SELECT MAX(T_RR2.ID_RATING_REQUEST)
            FROM "NEURON_PRO"."RATING"."T_RATING_REQUEST" T_RR2
            WHERE T_RR2.ID_EVALUACION = T_RATING_REQUEST.ID_EVALUACION
        ) -- Subquery to get the MAX ID_RATING_REQUEST for each evaluation
        GROUP BY ID_EVALUACION, T_RATING_REQUEST.ID_CLIENTE, T_RATING_REQUEST.ID_INPUT_CUSTOM_DATA, T_RATING_REQUEST.LAST_REQUEST, T_RATING_REQUEST.ESTADO, T_RATING_REQUEST.GRADE, T_RATING_REQUEST.PD
        ) T_RATING_REQUEST ON T_EVALUACION.ID_EVALUACION = T_RATING_REQUEST.ID_EVALUACION
        LEFT JOIN "NEURON_PRO"."RATING"."T_CLIENTE" T_CLIENTE ON T_RATING_REQUEST.ID_CLIENTE = T_CLIENTE.ID_CLIENTE
        LEFT JOIN "NEURON_PRO"."RATING"."T_MODEL_RESPONSE" T_MODEL_RESPONSE ON T_RATING_REQUEST.RATING_ID = T_MODEL_RESPONSE.RATING_ID
        LEFT JOIN (
            SELECT
                ID_EVALUACION,
                T_LIMITES_NEG.ID_TRAMO,
                T_LIMITES_NEG.ID_NEGOCIO,
                MAX(T_LIMITES_NEG.VOLUMEN) AS VOLUMEN,
                MAX(T_LIMITES_NEG.VOLUMEN_MAXIMO) AS VOLUMEN_MAXIMO,
                MAX(T_LIMITES_NEG.PRECIO) AS PRECIO
            FROM "NEURON_PRO"."RATING"."T_LIMITES_NEG" T_LIMITES_NEG
            GROUP BY ID_EVALUACION, T_LIMITES_NEG.ID_TRAMO, T_LIMITES_NEG.ID_NEGOCIO
        ) T_LIMITES_NEG ON T_EVALUACION.ID_EVALUACION = T_LIMITES_NEG.ID_EVALUACION
        LEFT JOIN "NEURON_PRO"."RATING"."T_LIMITES_GE" T_LIMITES_GE ON T_EVALUACION.ID_EVALUACION = T_LIMITES_GE.ID_EVALUACION
        LEFT JOIN "NEURON_PRO"."RATING"."T_CONFIG_NEGOCIO" T_CONFIG_NEGOCIO ON T_LIMITES_NEG.ID_NEGOCIO = T_CONFIG_NEGOCIO.ID_NEGOCIO
        LEFT JOIN "NEURON_PRO"."RATING"."T_CONFIG_TRAMO" T_CONFIG_TRAMO ON T_LIMITES_NEG.ID_TRAMO = T_CONFIG_TRAMO.ID_TRAMO
        LEFT JOIN "NEURON_PRO"."RATING"."T_ESTADO_MOROSO" T_ESTADO_MOROSO ON T_EVALUACION.ID_ESTADO_MOROSO = T_ESTADO_MOROSO.ID_ESTADO_MOROSO
        LEFT JOIN "NEURON_PRO"."RATING"."T_EVALUACION_DETALLE" T_EVALUACION_DETALLE ON T_EVALUACION.ID_EVALUACION = T_EVALUACION_DETALLE.ID_EVALUACION
        LEFT JOIN (
            SELECT
                EEFF.ID_EEFF,
                CODIGO_CNAE,
                ID_EVALUACION,
                GASTOS_FINANCIEROS,
                ING_EXPLOTACION,
                RESULT_ANTES_IMP,
                IMPORTE_NETO,
                TOTAL_PASIVO,
                FONDOS_PROPIOS,
                FECHA_BALANCE,
                FECHA_CONSTITUCION,
                FECHA_NOMBRAMIENTO AS FECHA_CONTRATACION
            FROM (
                SELECT
                    ID_EVALUACION,
                    MAX(T_EEFF.ID_EEFF) AS ID_EEFF
                FROM "NEURON_PRO"."RATING"."T_EEFF" T_EEFF
                LEFT JOIN "NEURON_PRO"."RATING"."T_REL_EVAL_EEFF" T_REL_EVAL_EEFF ON T_EEFF.ID_EEFF = T_REL_EVAL_EEFF.ID_EEFF
                GROUP BY ID_EVALUACION
            ) EEFF
            LEFT JOIN "NEURON_PRO"."RATING"."T_EEFF" T_EEFF2 ON T_EEFF2.ID_EEFF = EEFF.ID_EEFF
        ) T_EEFF ON T_EVALUACION.ID_EVALUACION = T_EEFF.ID_EVALUACION
        LEFT JOIN (
            SELECT
                T_EEFF_PT.ID_EEFF,
                RESULTADO_ANTES_IMPOSTO AS RESULT_ANTES_IMP_PT,
                DATA_DO_BALANCO AS FECHA_BALANCE_PT,
                TOTAL_DO_CAPITAL_PROPIO AS TOTAL_PASIVO_PT,
                (CAPITAL_REALIZADO + ACOES_PROPIAS + OUTROS_INST_CAP_PROPIO + PREMIOS_EMISSAO + RESERVAS_LEGAIS + OUTRAS_RESERVAS + RESULT_TRANSITADOS + RESULTADO_LIQUIDO + DIVIDENDOS_ANTECIPADOS) AS FONDOS_PROPIOS_PT,
                CODIGO_CAE,
                CONSTITUICAO AS FECHA_CONSTITUCION_PT,
                (VENDAS_E_SERV_PRESTADOS + OUTROS_RENDIMENTOS) AS ING_EXPLOTACION_PT,
                VENDAS_E_SERV_PRESTADOS AS IMPORTE_NETO_PT,
                (JUROS_E_REND_OBTIDOS + JUROS_E_GASTOS_SUPORT) AS GASTOS_FINANCIEROS_PT
            FROM (
                SELECT
                    ID_EEFF,
                    MAX(T_EEFF_PT.ID_EEFF_PT) AS ID_EEFF_PT
                FROM "NEURON_PRO"."RATING"."T_EEFF_PT" T_EEFF_PT
                LEFT JOIN "NEURON_PRO"."RATING"."T_REL_EEFF" T_REL_EEFF ON T_EEFF_PT.ID_EEFF_PT = T_REL_EEFF.ID_EEFF_PT
                GROUP BY ID_EEFF
            ) T_EEFF_PT
            LEFT JOIN "NEURON_PRO"."RATING"."T_EEFF_PT" T_EEFF_PT2 ON T_EEFF_PT.ID_EEFF_PT = T_EEFF_PT2.ID_EEFF_PT
        ) T_EEFF_PT ON T_EEFF.ID_EEFF = T_EEFF_PT.ID_EEFF
    ) Rating
        LEFT JOIN (
        SELECT DISTINCT
            ID_CLIENTE_FALCON_CRM,
            RATING_ID_CRM_FALCON,
            LEFT(FECHA_OFERTA, 10) AS FECHA_OFERTA,
            --COUNT(OFERTA) AS OFERTA,
            COUNT(CUPS) AS CUPS,
            COUNT(CONTRATO) AS CONTRATO,
            ESTADO_CRM_FALCON,
            ESTADO_FORMALIZADO,
            --ENTORNO,
            --BASE,
            CIUDAD_OFERTA
        FROM (
            SELECT
                QUOTEID AS OFERTA,
                NEW_FECHAINCIO AS FECHA_OFERTA,
                S2G_SCORINGID AS RATING_ID_CRM_FALCON,
                NEW_CUPS20 AS CUPS,
                CONTRACT.NEW_CIF AS ID_CLIENTE_FALCON_CRM,
                NEW_CODIGODECONTRATO AS CONTRATO,
                MAX(NEW_ESTADO) AS ESTADO_CRM_FALCON,
                MIN(CASE WHEN NEW_ESTADO = '31' THEN 'Formalizado' ELSE 'No_Formalizado' END) AS ESTADO_FORMALIZADO,
                NULL AS CIUDAD_OFERTA,
                NULL AS CODIGO_POSTAL_OFERTA,
                'CRM' AS ENTORNO,
                'OFERTA' AS BASE
            FROM "NEURON_PRO"."CRM_DYNAMICS"."QUOTE" QUOTE
            LEFT JOIN "NEURON_PRO"."CRM_DYNAMICS"."CONTRACT_EXTENSION_BASE" CONTRACT ON QUOTE.QUOTEID = CONTRACT.new_ofertadelaqueprovieneid
            GROUP BY
                OFERTA,
                FECHA_OFERTA,
                RATING_ID_CRM_FALCON,
                CUPS,
                CONTRATO,
                ID_CLIENTE_FALCON_CRM,
                CIUDAD_OFERTA,
                CODIGO_POSTAL_OFERTA
            UNION ALL
            SELECT
                FALCON_OBJ_QUOTE__C.ID AS OFERTA,
                FALCON_OBJ_QUOTE__C.CREATEDDATE AS FECHA_OFERTA,
                FALCON_FLD_RATINGID__C AS RATING_ID_CRM_FALCON,
                FALCON_FLD_DOCUMENTNUMBER__C AS ID_CLIENTE_FALCON_CMR,
                FALCON_OBJ_QUOTE__C.FALCON_FLD_CUPSAUX__C AS CUPS,
                FALCON_FLD_CONTRACTCODE2__C AS CONTRATO,
                MAX(CONTRACT.status) AS ESTADO_CRM_FALCON,
                MIN(CASE WHEN CONTRACT.status IN ('05', '07', '04') THEN 'Formalizado' ELSE 'No_Formalizado' END) AS ESTADO_FORMALIZADO,
                ACCOUNT.BILLINGCITY AS CIUDAD_OFERTA,
                ACCOUNT.BILLINGPOSTALCODE AS CODIGO_POSTAL_OFERTA,
                'FALCON' AS ENTORNO,
                'OFERTA' AS BASE
            FROM "NEURON_PRO"."SALESFORCE_REP"."FALCON_OBJ_QUOTE__C" FALCON_OBJ_QUOTE__C
            LEFT JOIN "NEURON_PRO"."SALESFORCE_REP"."CONTRACT" CONTRACT ON FALCON_OBJ_QUOTE__C.ID = CONTRACT.FALCON_fld_QuoteNew__c
            LEFT JOIN "NEURON_PRO"."SALESFORCE_REP"."ACCOUNT" ACCOUNT ON FALCON_OBJ_QUOTE__C.FALCON_FLD_ACCOUNTID__C = ACCOUNT.ID
            GROUP BY
                OFERTA,
                FECHA_OFERTA,
                RATING_ID_CRM_FALCON,
                ID_CLIENTE_FALCON_CMR,
                CUPS,
                CONTRATO,
                CIUDAD_OFERTA,
                CODIGO_POSTAL_OFERTA
        )
        GROUP BY
            ID_CLIENTE_FALCON_CRM,
            RATING_ID_CRM_FALCON,
            FECHA_OFERTA,
            ESTADO_CRM_FALCON,
            ESTADO_FORMALIZADO,
            ENTORNO,
            BASE,
            CIUDAD_OFERTA
    ) NewBusiness
    ON Rating.RATING_ID = NewBusiness.RATING_ID_CRM_FALCON)
    , RIESGO_VIVO_LAST AS (
        SELECT
            ID_CLIENTE,
            RIESGO_POWER,
            RIESGO_GAS,
            VOLUMEN AS VOLUMEN_RIESGO,
            RIESGO_POWER_FALCON,
            RIESGO_EFICIENCIA
        FROM "NEURON_PRO"."RATING"."T_RIESGO_VIVO"
        WHERE (ID_CLIENTE, FECHA_CREACION) IN (
            SELECT ID_CLIENTE, MAX(FECHA_CREACION)
            FROM "NEURON_PRO"."RATING"."T_RIESGO_VIVO"
            GROUP BY ID_CLIENTE
        )
    )
SELECT
    RATING.ID_EVALUACION AS "id_evaluacion",
    RATING.FECHA_CREACION AS "fecha_creacion",
    RATING.ANO_MES_CREACION AS "ano_mes_creacion",
    RATING.RATING_ID AS "rating_id",
    RATING.ESTADO AS "estado",
    RATING.ESTADO_DETALLE AS "estado_detalle",
    RATING.ID_CLIENTE AS "id_cliente",
    RATING.LAST_REQUEST AS "last_request",
    RATING.GRADE_OLD AS "grade_old",
    RATING.PD_OLD AS "pd_old",
    RATING.PD_NEW AS "pd_new",
    RATING.CIF_NIF AS "cif_nif",
    RATING.ZONA_GEOGRAFICA AS "zona_geografica",
    RATING.TIPO_PERSONA AS "tipo_persona",
    RATING.VOLUMEN AS "volumen",
    RATING.ID_TRAMO AS "id_tramo",
    RATING.ID_NEGOCIO AS "id_negocio",
    RATING.VOLUMEN_MAXIMO AS "volumen_maximo",
    RATING.PRECIO AS "precio",
    RATING.LIMITE_TOTAL_CONCEDIDO AS "limite_total_concedido",
    RATING.LIMITE_DISPONIBLE_GE AS "limite_disponible_ge",
    RATING.CONCURSO AS "concurso",
    RATING.BUROFAX AS "burofax",
    RATING.DEUDA_ASNEF AS "deuda_asnef",
    RATING.ASNEF AS "asnef",
    RATING.GASTOS_FINANCIEROS AS "gastos_financieros",
    RATING.ING_EXPLOTACION AS "ing_explotacion",
    RATING.RESULT_ANTES_IMP AS "result_antes_imp",
    RATING.IMPORTE_NETO AS "importe_neto",
    RATING.TOTAL_PASIVO AS "total_pasivo",
    RATING.FONDOS_PROPIOS AS "fondos_propios",
    RATING.FECHA_BALANCE AS "fecha_balance",
    RATING.FECHA_CONSTITUCION AS "fecha_constitucion",
    RATING.FECHA_CONTRATACION AS "fecha_contratacion",
    RATING.CODIGO_CNAE AS "codigo_cnae",
    RATING.RESULT_ANTES_IMP_PT AS "result_antes_imp_pt",
    RATING.FECHA_BALANCE_PT AS "fecha_balance_pt",
    RATING.TOTAL_PASIVO_PT AS "total_pasivo_pt",
    RATING.FONDOS_PROPIOS_PT AS "fondos_propios_pt",
    RATING.FECHA_CONSTITUCION_PT AS "fecha_constitucion_pt",
    RATING.ING_EXPLOTACION_PT AS "ing_explotacion_pt",
    RATING.IMPORTE_NETO_PT AS "importe_neto_pt",
    RATING.GASTOS_FINANCIEROS_PT AS "gastos_financieros_pt",
    RIESGO_VIVO_LAST.ID_CLIENTE AS "id_cliente_riesgo_vivo",
    RIESGO_VIVO_LAST.RIESGO_POWER AS "riesgo_vivo_power",
    RIESGO_VIVO_LAST.RIESGO_GAS AS "riesgo_vivo_gas",
    RIESGO_VIVO_LAST.VOLUMEN_RIESGO AS "volumen_riesgo",
    RIESGO_VIVO_LAST.RIESGO_POWER_FALCON AS "riesgo_vivo_power_falcon",
    RIESGO_VIVO_LAST.RIESGO_EFICIENCIA AS "riesgo_vivo_eficiencia"
FROM RATING
LEFT JOIN RIESGO_VIVO_LAST ON RATING.ID_CLIENTE = RIESGO_VIVO_LAST.ID_CLIENTE
